/** @format */

import type { NextPage } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";

import Header from "../Components/Header";
import styles from "../styles/Home.module.css";
import PostCard from "../Components/PostCard";
import { HomeProps, Post } from "../Constants/CommonConstants";
import { CardsContainer, LoadMore } from "../Components/StyledComponents";
const Home: NextPage = (props: HomeProps) => {
  const [pageNum, setPageNum] = useState<number>(1);
  const [postsList, setPostsList] = useState<[Post]>();
  useEffect(() => {
    setPostsList(props.posts);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <CardsContainer>
        {props.posts.map((post) => (
          <PostCard post={post} />
        ))}
      </CardsContainer>
      <LoadMore>Load More</LoadMore>
    </div>
  );
};
export async function getServerSideProps() {
  const res = await fetch(`https://dummyapi.io/data/v1/post?page=1&limit=8`, {
    headers: { "app-id": "61fdc5feccc5eb03c2b64a7e" },
  });
  let posts = await res.json();
  posts = posts.data;
  // Pass data to the page via props
  return { props: { posts } };
}
export default Home;
